-
  name: deploy http-service container
  docker_container:
    name: http-service
    hostname: http-service.local
    networks:
      - name: "{{ docker.network }}"
    image: "runelite/http-service:{{ version }}"
    restart_policy: always
    ports:
    - "9080:8080"
    links:
      - db
      - minio
      - redis
    env:
      spring_profiles_active: dev
      SPRING_APPLICATION_JSON: "{{ spring_config | to_json }}"
