-
  name: deploy cache-updater container
  docker_container:
    name: cache-updater
    hostname: cache-updater.local
    networks:
      - name: "{{ docker.network }}"
    image: "runelite/cache-updater:{{ version }}"
    restart_policy: on-failure
    links:
      - db
      - minio
