-
  name: ensure {{ directory }}/cache-updater dir exists
  file: path="{{ directory }}/cache-updater" state=directory
-
  name: download cache-updater distribution
  get_url:
    url: "http://repo.runelite.net/net/runelite/cache-updater/{{ cache_version }}/cache-updater-{{ cache_version }}-spring-boot.jar"
    dest: "{{ directory }}/cache-updater/cache-updater-{{ cache_version }}.jar"
    checksum: sha256:19fab0ab9102e33cd3eb8807ca5f8c64afc7c341e5ab48fa56f4136125183b17
-
  name: write docker build file
  copy:
    src: Dockerfile
    dest: "{{ directory }}/cache-updater"

- name: build cache-updater image
  docker_image:
    name: runelite/cache-updater
    tag: "{{ cache_version }}"
    path: "{{ directory }}/cache-updater"
    buildargs:
      JAR_FILE: "cache-updater-{{ cache_version }}.jar"
-
  name: deploy cache-updater container
  docker_container:
    name: cache-updater
    hostname: cache-updater.local
    networks:
      - name: "{{ docker.network }}"
    image: "runelite/cache-updater:{{ cache_version }}"
    restart_policy: on-failure
    links:
      - db
      - minio
    env:
      SPRING_APPLICATION_JSON: "{{ spring_config | to_json }}"
