-
  name: ensure {{ directory }}/session-service dir exists
  file: path="{{ directory }}/session-service" state=directory
-
  name: download session-service distribution
  get_url:
    url: "https://github.com/runelite/session-service/releases/download/{{ services.session.version }}/runelite-session"
    dest: "{{ directory }}/session-service/runelite-session-{{ services.session.version }}"
    checksum: "{{ services.session.checksum }}"
-
  name: write docker build file
  copy:
    src: Dockerfile
    dest: "{{ directory }}/session-service"

- name: build session-service image
  docker_image:
    name: runelite/session-service
    tag: "{{ services.session.version }}"
    path: "{{ directory }}/session-service"
    buildargs:
      BIN_FILE: "runelite-session-{{ services.session.version }}"
-
  name: deploy session-service container
  docker_container:
    name: session-service
    hostname: session-service.local
    networks:
      - name: "{{ docker.network }}"
    image: "runelite/session-service:{{ services.session.version }}"
    restart_policy: on-failure
    links:
      - redis
    env:
      REDIS_HOST: "redis:6379"
