-
  name: ensure {{ directory }}/session-service dir exists
  file: path="{{ directory }}/session-service" state=directory
-
  name: download session-service distribution
  get_url:
    url: "https://github.com/runelite/session-service/releases/download/{{ session_service_version }}/runelite-session"
    dest: "{{ directory }}/session-service/runelite-session-{{ session_service_version }}"
    checksum: sha256:a2b7c6cdbb0e02a240c9cf404f282c704c3a1fc6237cdb579e9d1501fae86bf8
-
  name: write docker build file
  copy:
    src: Dockerfile
    dest: "{{ directory }}/session-service"

- name: build session-service image
  docker_image:
    name: runelite/session-service
    tag: "{{ session_service_version }}"
    path: "{{ directory }}/session-service"
    buildargs:
      BIN_FILE: "runelite-session-{{ session_service_version }}"
-
  name: deploy session-service container
  docker_container:
    name: session-service
    hostname: session-service.local
    networks:
      - name: "{{ docker.network }}"
    image: "runelite/session-service:{{ session_service_version }}"
    restart_policy: on-failure
    links:
      - redis
    env:
      REDIS_HOST: "redis:6379"
