---
-
  hosts:
    - localhost
    - all
  roles:
    - { role: centos, when: ansible_distribution == 'CentOS' }
    - network
    - database
    - minio
    - redis
    - cache-updater
    - tomcat
    - http-service
  vars_files:
    - vars.yml
