---
-
  hosts:
    - all
    - localhost
  vars_files:
    - vars.yml
  tasks:
    -
      name: "Write the mysql init sql file"
      template:
        dest: mysql/init/init.sql
        src: templates/init.sql.j2
    -
      name: "Launch database container"
      docker_container:
        name: db
        image: "mariadb:10.2.16"
        command: "--plugin-dir=/docker-entrypoint-dbplugins"
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: "{{ database.root_password }}"
        volumes:
          - "./mysql/init/:/docker-entrypoint-initdb.d"
          - "./mysql/plugins/:/docker-entrypoint-dbplugins"
    -
      name: "Get database IP address"
      command: "docker inspect --format '{''{ .NetworkSettings.IPAddress }''}' db"
      register: mariadb_ip_address
    -
      name: "Wait for database to become ready"
      wait_for:
        host: "{{ mariadb_ip_address.stdout }}"
        port: 3306
        state: started
        connect_timeout: 15
        delay: 5
        timeout: 30
    -
      name: "Write the tomcat context xml file"
      template:
        dest: tomcat/conf/context.xml
        src: templates/context.xml.j2
    -
      name: "Write the tomcat server xml file"
      template:
        dest: tomcat/conf/server.xml
        src: templates/server.xml.j2
    -
      name: "Write the tomcat users xml file"
      template:
        dest: tomcat/conf/tomcat-users.xml
        src: templates/tomcat-users.xml.j2
    -
      name: "Download HikariCP 3.2.0"
      get_url:
        url: "http://central.maven.org/maven2/com/zaxxer/HikariCP/3.2.0/HikariCP-3.2.0.jar"
        dest: tomcat/lib/hikaricp.jar
    -
      name: "Download MariaDB connector 2.2.6"
      get_url:
        url: "https://downloads.mariadb.com/Connectors/java/connector-java-2.2.6/mariadb-java-client-2.2.6.jar"
        dest: tomcat/lib/mariadb-connector.jar
    -
      name: "Download Slf4j API 1.7.25"
      get_url:
        url: "http://central.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar"
        dest: tomcat/lib/slf4j-api.jar
    -
      name: "Launch tomcat container"
      docker_container:
        name: web
        image: "tomcat:8"
        restart: true
        ports:
          - "80:8080"
        links:
          - db
        volumes:
          - "./tomcat/lib/hikaricp.jar:/usr/local/tomcat/lib/hikaricp.jar"
          - "./tomcat/lib/mariadb-connector.jar:/usr/local/tomcat/lib/mariadb-connector.jar"
          - "./tomcat/lib/slf4j-api.jar:/usr/local/tomcat/lib/slf4j-api.jar"
          - "./tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml"
          - "./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml"
          - "./tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
          - "./tomcat/conf/manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml"
