---
-
  hosts:
    - localhost
    - all
  roles:
    - { role: centos, when: ansible_distribution == 'CentOS' }
    - network
    - database
    - minio
    - redis
    - cache-updater
    - { role: tomcat, when: with_tomcat is defined }
    - { role: http-service, when: with_tomcat is not defined }
  vars_files:
    - vars.yml
