---
-
  hosts:
    - localhost
    - all
  roles:
    - { role: centos, when: ansible_distribution == 'CentOS' }
    - network
    - mariadb
    - minio
    - redis
    - mongo
    - session-service
    - ws-service
  vars_files:
    - vars.yml
