-
  name: ensure {{ directory }}/ws-service dir exists
  file: path="{{ directory }}/ws-service" state=directory
-
  name: download ws-service distribution
  get_url:
    url: "https://github.com/deathbeam/runelite-ws/releases/download/{{ services.ws.version }}/runelite-ws"
    dest: "{{ directory }}/ws-service/runelite-ws-{{ services.ws.version }}"
    checksum: "{{ services.ws.checksum }}"
-
  name: write docker build file
  copy:
    src: Dockerfile
    dest: "{{ directory }}/ws-service"

- name: build ws-service image
  docker_image:
    name: runelite/ws-service
    tag: "{{ services.ws.version }}"
    path: "{{ directory }}/ws-service"
    buildargs:
      BIN_FILE: "runelite-ws-{{ services.ws.version }}"
-
  name: deploy ws-service container
  docker_container:
    name: ws-service
    hostname: ws-service.local
    networks:
      - name: "{{ docker.network }}"
    image: "runelite/ws-service:{{ services.ws.version }}"
    restart_policy: on-failure
    links:
      - redis
    ports:
      - "8081:8081"
    env:
      REDIS_HOST: "redis:6379"
