-
  name: deploy minio container
  docker_container:
    name: minio
    hostname: minio.local
    networks:
      - name: "{{ docker.network }}"
    image: "minio/minio"
    restart_policy: always
    ports:
      - "9000:9000"
    entrypoint: sh
    command: "-c 'mkdir -p /export/{{ minio.bucket }} && /usr/bin/minio server /export'"
    env:
      MINIO_ACCESS_KEY: "{{ minio.accesskey }}"
      MINIO_SECRET_KEY: "{{ minio.secretkey }}"
    volumes:
      - "/mnt/minio-data/:/export"
      - "/mnt/minio-config/:/root/.minio"
